# Aggregate the single-cell profiles to the well level
This notebook is not run as a large amount of RAM is needed to run it. It is provided for reference only.

In [1]:
import os
import pathlib
import pprint

import pandas as pd
from pycytominer import aggregate
from pycytominer.cyto_utils import output
from timelapse_utils.file_utils.notebook_init_utils import (
    bandicoot_check,
    init_notebook,
)
from timelapse_utils.profiling_utils.sc_extraction_utils import add_single_cell_count_df

root_dir, in_notebook = init_notebook()
if in_notebook:
    import tqdm.notebook as tqdm
else:
    import tqdm

In [4]:
# load in platemap file as a pandas dataframe
platemap_path = pathlib.Path(
    f"{root_dir}/Wave2_data/0.download_data/platemap/platemap.csv"
).resolve()

image_base_dir = bandicoot_check(
    bandicoot_mount_path=pathlib.Path(f"{os.path.expanduser('~')}/mnt/bandicoot/"),
    root_dir=root_dir,
)
image_base_dir = pathlib.Path(
    f"{image_base_dir}/live_cell_timelapse_pyroptosis_project_data/processed_data/"
).resolve(strict=True)
normalized_profiles_path = pathlib.Path(
    f"{image_base_dir}/8.normalized_profiles/normalized_profiles.parquet"
).resolve(strict=True)
chammi_profiles_path = pathlib.Path(
    f"{image_base_dir}/7a.CHAMMI75_extracted_features/CHAMMI75_combined_sc_profiles.parquet"
).resolve(strict=True)

In [5]:
norm_CP_df = pd.read_parquet(normalized_profiles_path)
chammi75_df = pd.read_parquet(chammi_profiles_path)
print("Shape of profiles:")
print(f"Normalized CP: {norm_CP_df.shape[0]}")
print(f"CHAMMI75: {chammi75_df.shape[0]}")

Shape of profiles:
Normalized CP: 4627
CHAMMI75: 1137

In [7]:
norm_CP_df

,Metadata_Well,Metadata_Inducer,Metadata_Inducer_dose,Metadata_Inhibitor,Metadata_Inhibitor_dose,Metadata_Time,Metadata_Well_FOV,Metadata_FOV,Metadata_Well_FOV_Time,Metadata_ImageNumber,...,Nuclei_Texture_Variance_CL640_3_02_256,Nuclei_Texture_Variance_CL640_3_03_256,Nuclei_Texture_Variance_NucleoLive_3_00_256,Nuclei_Texture_Variance_NucleoLive_3_01_256,Nuclei_Texture_Variance_NucleoLive_3_02_256,Nuclei_Texture_Variance_NucleoLive_3_03_256,Nuclei_Texture_Variance_SYTOXGreen_3_00_256,Nuclei_Texture_Variance_SYTOXGreen_3_01_256,Nuclei_Texture_Variance_SYTOXGreen_3_02_256,Nuclei_Texture_Variance_SYTOXGreen_3_03_256
0,B2,DMSO,0.15%,DMSO,0.15%,1,B2_1,1,B2_1_1,1,...,-0.630030,-0.609157,-0.117126,-0.117563,-0.117299,-0.116842,-0.055075,-0.055393,-0.055116,-0.055422
1,B2,DMSO,0.15%,DMSO,0.15%,1,B2_1,1,B2_1_1,1,...,-0.686866,-0.654088,-0.117126,-0.117563,-0.117299,-0.116842,-0.055075,-0.055393,-0.055116,-0.055422
2,B2,DMSO,0.15%,DMSO,0.15%,1,B2_1,1,B2_1_1,1,...,0.024110,0.038246,-0.117126,-0.117563,-0.117299,-0.116842,-0.055075,-0.055393,-0.055116,-0.055422
3,B2,DMSO,0.15%,DMSO,0.15%,1,B2_1,1,B2_1_1,1,...,-0.664616,-0.611108,-0.117126,-0.117563,-0.117299,-0.116842,-0.055075,-0.055393,-0.055116,-0.055422
4,B2,DMSO,0.15%,DMSO,0.15%,1,B2_1,1,B2_1_1,1,...,-0.742793,-0.728319,-0.117126,-0.117563,-0.117299,-0.116842,-0.055075,-0.055393,-0.055116,-0.055422
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4622,B2,DMSO,0.15%,DMSO,0.15%,4,B2_1,1,B2_1_4,1,...,2.239362,2.153946,-0.008338,-0.001281,-0.000886,-0.007995,-0.055075,-0.055393,-0.055116,-0.055422
4623,B2,DMSO,0.15%,DMSO,0.15%,4,B2_1,1,B2_1_4,1,...,-0.409592,-0.403055,-0.077796,-0.073963,-0.075776,-0.075279,-0.055075,-0.055393,-0.055116,-0.055422
4624,B2,DMSO,0.15%,DMSO,0.15%,4,B2_1,1,B2_1_4,1,...,0.308877,0.331125,-0.117126,-0.117563,-0.117299,-0.116842,-0.055075,-0.055393,-0.055116,-0.055422
4625,B2,DMSO,0.15%,DMSO,0.15%,4,B2_1,1,B2_1_4,1,...,0.257248,0.275399,-0.117126,-0.117563,-0.117299,-0.116842,-0.055075,-0.055393,-0.055116,-0.055422
4626,B2,DMSO,0.15%,DMSO,0.15%,4,B2_1,1,B2_1_4,1,...,-0.745290,-0.721997,-0.117126,-0.117563,-0.117299,-0.116842,-0.055075,-0.055393,-0.055116,-0.055422

In [8]:
merged_df = pd.merge(
    norm_CP_df,
    chammi75_df,
    on=[
        "Metadata_Well_FOV",
        "Metadata_Time",
        "Metadata_Nuclei_Number_Object_Number",
        "Metadata_Cells_AreaShape_Center_X",
        "Metadata_Cells_AreaShape_Center_Y",
    ],
    how="left",
)
print(f"Merged profiles: {merged_df.shape[0]}")

Merged profiles: 4627

In [10]:
merged_df

,Metadata_Well,Metadata_Inducer,Metadata_Inducer_dose,Metadata_Inhibitor,Metadata_Inhibitor_dose,Metadata_Time,Metadata_Well_FOV,Metadata_FOV,Metadata_Well_FOV_Time,Metadata_ImageNumber,...,Nucleocentric_SYTOXGreen_CHAMMI75_Feature90,Nucleocentric_SYTOXGreen_CHAMMI75_Feature91,Nucleocentric_SYTOXGreen_CHAMMI75_Feature92,Nucleocentric_SYTOXGreen_CHAMMI75_Feature93,Nucleocentric_SYTOXGreen_CHAMMI75_Feature94,Nucleocentric_SYTOXGreen_CHAMMI75_Feature95,Nucleocentric_SYTOXGreen_CHAMMI75_Feature96,Nucleocentric_SYTOXGreen_CHAMMI75_Feature97,Nucleocentric_SYTOXGreen_CHAMMI75_Feature98,Nucleocentric_SYTOXGreen_CHAMMI75_Feature99
0,B2,DMSO,0.15%,DMSO,0.15%,1,B2_1,1,B2_1_1,1,...,1.023240,1.254434,-5.106654,3.973393,4.420975,2.096377,-1.455441,1.754054,0.756196,2.069703
1,B2,DMSO,0.15%,DMSO,0.15%,1,B2_1,1,B2_1_1,1,...,1.118941,1.750928,-4.207298,4.641288,5.062917,1.886621,-1.790866,2.684594,1.007277,1.772836
2,B2,DMSO,0.15%,DMSO,0.15%,1,B2_1,1,B2_1_1,1,...,1.056204,1.504928,-4.435646,4.207762,3.852463,1.584646,-0.776207,1.837654,0.255680,0.995764
3,B2,DMSO,0.15%,DMSO,0.15%,1,B2_1,1,B2_1_1,1,...,1.022551,0.869031,-5.359560,4.268159,4.884048,2.598779,-1.734051,1.474915,0.430418,2.043305
4,B2,DMSO,0.15%,DMSO,0.15%,1,B2_1,1,B2_1_1,1,...,1.193125,1.376956,-5.014697,5.400067,4.056452,2.430958,-1.970731,1.144398,-0.105689,1.925226
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4622,B2,DMSO,0.15%,DMSO,0.15%,4,B2_1,1,B2_1_4,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4623,B2,DMSO,0.15%,DMSO,0.15%,4,B2_1,1,B2_1_4,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4624,B2,DMSO,0.15%,DMSO,0.15%,4,B2_1,1,B2_1_4,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4625,B2,DMSO,0.15%,DMSO,0.15%,4,B2_1,1,B2_1_4,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4626,B2,DMSO,0.15%,DMSO,0.15%,4,B2_1,1,B2_1_4,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN